### ISSUE TITLE
Create Terraform module

### ISSUE THREAD

**Issue by tribaljack** [quintilesims/k8-auth0-authenticator#1]
From what we've gathered, it is much easier to configure K8 clusters with custom authenticators when said authenticator is accessible via public internet. This work item includes creating a Terraform module for this service to run on AWS, which will make it easy for developers to get this service running and accessible via public internet.

**Comment by zpatrick** [comment]
module is located here: https://github.com/quintilesims/k8-auth0-authenticator/tree/master/terraform
